window:
  # decorations: buttonless
  padding:
    x: 8
    y: 4

background_opacity: 0.97

font:
  normal:
    family: Fira Code
  bold:
    family: Fira Code
  italic:
    family: Fira Code
  bold_italic:
    family: Fira Code

  size: 13
  use_thin_strokes: true
  offset:
    x: 0
    y: 3
