[tools]
bun = "latest"
erlang = "28"
elixir = "1.19"
node = "24"
"npm:@fission-ai/openspec" = "1.1"
"npm:@google/gemini-cli" = "0.27.0"
"npm:@mariozechner/pi-coding-agent" = "0.51.6"
"npm:@openai/codex" = "latest"
"npm:yarn" = "1.22.22"
serverless = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
package_manager = "bun"
